#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Main entry point of the application.

The app can be run by loading this module. It runs front.main() and
shows a nice message on errors.
"""


import sys
import my_env

try:
    if not my_env.is_frozen:
        # See http://www.wxpython.org/docs/api/wxversion-module.html
        import wxversion
        wxversion.select(["2.9.5", "3.0"])
    import front
    front.main()
except SystemExit as e:
    sys.exit(e.code)
except:
    import traceback
    exc_type, exc_obj, exc_tb = sys.exc_info()
    tname = exc_type.__name__
    text = "\n".join(str(i) for i in exc_obj.args)

    if "--debug" in sys.argv:
        text += ("\n\nTraceback:\n    " +
                 "    ".join(traceback.format_tb(exc_tb)))

    try:
        import wx
        app = wx.App()
        wx.MessageBox(
            "An error happened\n\n%s: %s" % (tname, text),
            "Startup error",
            wx.ICON_ERROR | wx.OK)
        del app
    except:
        print >> sys.stderr, "Startup error\n%s: %s" % (tname, text)
